on:
  push:
  pull_request:
  workflow_dispatch:

  # Run automatically every monday
  schedule:
    - cron: 1 12 * * 1

name: CI

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable components
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --release -- -D warnings

  build_and_test:
    name: Rust project
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'ubuntu-latest', 'ubuntu-20.04', 'windows-latest']
        rust: ['stable']
        include:
          - os: 'ubuntu-20.04'
            rust: '1.41'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v4
        with:
          name: plotsweep ${{ matrix.os }} rust-${{ matrix.rust }}
          path: |
            target/release/plotsweep
            target/release/plotsweep.exe
